-   id: helm-lint
    name: helm-lint
    description: 'Run helm lint exluding all files'
    entry: hooks/helm-lint.sh
    language: script
    pass_filenames: false
    always_run: true
    require_serial: true
